package com.InceptionWork.inception.registry;

import com.InceptionWork.inception.inception;
import com.InceptionWork.inception.block.BlockBase;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.item.Item;
import net.minecraft.item.ItemStack;

public class TabInception {
    private static Block icon;

    public static void init() {
        final Block INC_CARPET_ONE = new BlockBase(Material.CARPET, "inc_carpet_one", inception.INCEPTION_TAB);
        final Block INC_ASPHALT = new BlockBase(Material.ROCK, "inc_asphalt", inception.INCEPTION_TAB);
        final Block INC_MARBLE = new BlockBase(Material.ROCK, "inc_marble", inception.INCEPTION_TAB);
        final Block INC_FROSTED = new BlockBase(Material.ROCK, "inc_frosted", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_PREFABRICATED = new BlockBase(Material.ROCK, "inc_concrete_prefabricated", inception.INCEPTION_TAB);
        final Block INC_CERAMIC = new BlockBase(Material.ROCK, "inc_ceramic", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_PATTERN = new BlockBase(Material.ROCK, "inc_ceramic_pattern", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_SECOND = new BlockBase(Material.ROCK, "inc_ceramic_second", inception.INCEPTION_TAB);
        final Block INC_CONCRETE = new BlockBase(Material.ROCK, "inc_concrete", inception.INCEPTION_TAB);
        final Block INC_DECK = new BlockBase(Material.ROCK, "inc_deck", inception.INCEPTION_TAB);
        final Block INC_FLOOR_FIRST = new BlockBase(Material.ROCK, "inc_floor_first", inception.INCEPTION_TAB);
        final Block INC_FLOOR_SECOND = new BlockBase(Material.ROCK, "inc_floor_second", inception.INCEPTION_TAB);
        final Block INC_GRAVEL = new BlockBase(Material.ROCK, "inc_gravel", inception.INCEPTION_TAB);
        final Block INC_GRAVEL_BROKEN = new BlockBase(Material.ROCK, "inc_gravel_broken", inception.INCEPTION_TAB);
        final Block INC_MARBLE_BLACK = new BlockBase(Material.ROCK, "inc_marble_black", inception.INCEPTION_TAB);
        final Block INC_MARBLE_GRAY = new BlockBase(Material.ROCK, "inc_marble_gray", inception.INCEPTION_TAB);
        final Block INC_MARBLE_RANDOM = new BlockBase(Material.ROCK, "inc_marble_random", inception.INCEPTION_TAB);
        final Block INC_MARBLE_ROUGH_BLACK = new BlockBase(Material.ROCK, "inc_marble_rough_black", inception.INCEPTION_TAB);
        final Block INC_OAK = new BlockBase(Material.ROCK, "inc_oak", inception.INCEPTION_TAB);
        final Block INC_PINEWOOD = new BlockBase(Material.ROCK, "inc_pinewood", inception.INCEPTION_TAB);
        final Block INC_PLASTIC = new BlockBase(Material.ROCK, "inc_plastic", inception.INCEPTION_TAB);
        final Block INC_PLYWOOD = new BlockBase(Material.ROCK, "inc_plywood", inception.INCEPTION_TAB);
        final Block INC_POLYGON_STITCHING = new BlockBase(Material.ROCK, "inc_polygon_stitching", inception.INCEPTION_TAB);
        final Block INC_RECTANGLE_STITCHING = new BlockBase(Material.ROCK, "inc_rectangle_stitching", inception.INCEPTION_TAB);
        final Block INC_SANDSTONE_CULTURE = new BlockBase(Material.ROCK, "inc_sandstone_culture", inception.INCEPTION_TAB);
        final Block INC_TERRAZZO = new BlockBase(Material.ROCK, "inc_terrazzo", inception.INCEPTION_TAB);
        final Block INC_VERTICAL_STRIPES_DIRTY = new BlockBase(Material.ROCK, "inc_vertical_stripes_dirty", inception.INCEPTION_TAB);
        final Block INC_WOOD_HERRINGBONE = new BlockBase(Material.ROCK, "inc_wood_herringbone", inception.INCEPTION_TAB);
        final Block INC_WOOD_OUTDOOR = new BlockBase(Material.ROCK, "inc_wood_outdoor", inception.INCEPTION_TAB);
        final Block INC_WOOD_SMOOTH = new BlockBase(Material.ROCK, "inc_wood_smooth", inception.INCEPTION_TAB);
        final Block INC_WOOD_STAGGER = new BlockBase(Material.ROCK, "inc_wood_stagger", inception.INCEPTION_TAB);
        final Block INC_WOOD_STRIPE = new BlockBase(Material.ROCK, "inc_wood_stripe", inception.INCEPTION_TAB);
        final Block INC_WOOD_VERTICAL_STRIPES = new BlockBase(Material.ROCK, "inc_wood_vertical_stripes", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_WHITE = new BlockBase(Material.ROCK, "inc_concrete_white", inception.INCEPTION_TAB);
        final Block INC_CARPET_TWO = new BlockBase(Material.ROCK, "inc_carpet_two", inception.INCEPTION_TAB);
        final Block INC_CARPET_THREE = new BlockBase(Material.ROCK, "inc_carpet_three", inception.INCEPTION_TAB);
        final Block INC_CARPET_FOUR = new BlockBase(Material.ROCK, "inc_carpet_four", inception.INCEPTION_TAB);
        final Block INC_CARPET_FIVE = new BlockBase(Material.ROCK, "inc_carpet_five", inception.INCEPTION_TAB);
        final Block INC_CARPET_SIX = new BlockBase(Material.ROCK, "inc_carpet_six", inception.INCEPTION_TAB);
        final Block INC_CARPET_SEVEN = new BlockBase(Material.ROCK, "inc_carpet_seven", inception.INCEPTION_TAB);
        final Block INC_CARPET_EIGHT = new BlockBase(Material.ROCK, "inc_carpet_eight", inception.INCEPTION_TAB);
        final Block INC_CARPET_NINE = new BlockBase(Material.ROCK, "inc_carpet_nine", inception.INCEPTION_TAB);
        final Block INC_CARPET_TEN = new BlockBase(Material.ROCK, "inc_carpet_ten", inception.INCEPTION_TAB);
        final Block INC_CARPET_ELEVEN = new BlockBase(Material.ROCK, "inc_carpet_eleven", inception.INCEPTION_TAB);
        final Block INC_CARPET_TWELVE = new BlockBase(Material.ROCK, "inc_carpet_twelve", inception.INCEPTION_TAB);
        final Block INC_CARPET_THIRTEEN = new BlockBase(Material.ROCK, "inc_carpet_thirteen", inception.INCEPTION_TAB);
        final Block INC_CARPET_FOURTEEN = new BlockBase(Material.ROCK, "inc_carpet_fourteen", inception.INCEPTION_TAB);
        final Block INC_CARPET_FIFTEEN = new BlockBase(Material.ROCK, "inc_carpet_fifteen", inception.INCEPTION_TAB);
        final Block INC_CARPET_SIXTEEN = new BlockBase(Material.ROCK, "inc_carpet_sixteen", inception.INCEPTION_TAB);
        final Block INC_CARPET_SEVENTEEN = new BlockBase(Material.ROCK, "inc_carpet_seventeen", inception.INCEPTION_TAB);
        final Block INC_CARPET_EIGHTEEN = new BlockBase(Material.ROCK, "inc_carpet_eighteen", inception.INCEPTION_TAB);
        final Block INC_ICE_BLOCK = new BlockBase(Material.ROCK, "inc_ice_block", inception.INCEPTION_TAB);
        final Block INC_GOLD_BLOCK = new BlockBase(Material.ROCK, "inc_gold_block", inception.INCEPTION_TAB);
        final Block INC_IRON_BLOCK = new BlockBase(Material.ROCK, "inc_iron_block", inception.INCEPTION_TAB);
        final Block INC_STONE = new BlockBase(Material.ROCK, "inc_stone", inception.INCEPTION_TAB);
        final Block INC_STONE_WALL = new BlockBase(Material.ROCK, "inc_stone_wall", inception.INCEPTION_TAB);
        final Block INC_COAL = new BlockBase(Material.ROCK, "inc_coal", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_GRAY = new BlockBase(Material.ROCK, "inc_concrete_gray", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_TWO = new BlockBase(Material.ROCK, "inc_concrete_two", inception.INCEPTION_TAB);
        final Block INC_DAMASCUS_STEEL = new BlockBase(Material.ROCK, "inc_damascus_steel", inception.INCEPTION_TAB);
        final Block INC_GRANITE = new BlockBase(Material.ROCK, "inc_granite", inception.INCEPTION_TAB);
        final Block INC_KITCHEN_RANGE = new BlockBase(Material.ROCK, "inc_kitchen_range", inception.INCEPTION_TAB);
        final Block INC_MARBLE_SLAB = new BlockBase(Material.ROCK, "inc_marble_slab", inception.INCEPTION_TAB);
        final Block INC_MIRROR = new BlockBase(Material.ROCK, "inc_mirror", inception.INCEPTION_TAB);
        final Block INC_TABLECLOTH = new BlockBase(Material.ROCK, "inc_tablecloth", inception.INCEPTION_TAB);
        final Block INC_WOOD_WHITE_HORIZONTAL = new BlockBase(Material.ROCK, "inc_wood_white_horizontal", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_POWDER_WHITE = new BlockBase(Material.ROCK, "inc_concrete_powder_white", inception.INCEPTION_TAB);
        final Block INC_MARBLE_ROUGH_WHITE = new BlockBase(Material.ROCK, "inc_marble_rough_white", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_LATTICE_WHITE = new BlockBase(Material.ROCK, "inc_ceramic_lattice_white", inception.INCEPTION_TAB);
        final Block INC_BAD_PLANK = new BlockBase(Material.ROCK, "inc_bad_plank", inception.INCEPTION_TAB);
        final Block INC_KITCHEN_CERAMIC = new BlockBase(Material.ROCK, "inc_kitchen_ceramic", inception.INCEPTION_TAB);
        final Block INC_HIGHLY_REFLECTIVE = new BlockBase(Material.ROCK, "inc_highly_reflective", inception.INCEPTION_TAB);
        final Block INC_WALL_WHITE = new BlockBase(Material.ROCK, "inc_wall_white", inception.INCEPTION_TAB);
        final Block INC_WOOD_LIGHT_STAGGER = new BlockBase(Material.ROCK, "inc_wood_light_stagger", inception.INCEPTION_TAB);
        final Block INC_PLYWOOD_LIGHT = new BlockBase(Material.ROCK, "inc_plywood_light", inception.INCEPTION_TAB);
        final Block INC_CROCODILE_LEATHER = new BlockBase(Material.ROCK, "inc_crocodile_leather", inception.INCEPTION_TAB);
        final Block INC_ANTI_SLIP_METAL = new BlockBase(Material.ROCK, "inc_anti_slip_metal", inception.INCEPTION_TAB);
        final Block INC_STONE_BRICKS = new BlockBase(Material.ROCK, "inc_stone_bricks", inception.INCEPTION_TAB);
        final Block INC_MARBLE_BLUE = new BlockBase(Material.ROCK, "inc_marble_blue", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_LATTICE_YELLOW = new BlockBase(Material.ROCK, "inc_ceramic_lattice_yellow", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_STAGGER_BRICKS = new BlockBase(Material.ROCK, "inc_concrete_stagger_bricks", inception.INCEPTION_TAB);
        final Block INC_LUXURIOUS_LEATHER = new BlockBase(Material.ROCK, "inc_luxurious_leather", inception.INCEPTION_TAB);
        final Block INC_ELECTRICAL_METAL = new BlockBase(Material.ROCK, "inc_electrical_metal", inception.INCEPTION_TAB);
        final Block INC_PLYWOOD_RECTANGLE = new BlockBase(Material.ROCK, "inc_plywood_rectangle", inception.INCEPTION_TAB);
        final Block INC_PLYWOOD_HEXAGON = new BlockBase(Material.ROCK, "inc_plywood_hexagon", inception.INCEPTION_TAB);
        final Block INC_LINEN = new BlockBase(Material.ROCK, "inc_linen", inception.INCEPTION_TAB);
        final Block INC_LEATHER = new BlockBase(Material.ROCK, "inc_leather", inception.INCEPTION_TAB);
        final Block INC_SKIN_STRIAE_BRICKS = new BlockBase(Material.ROCK, "inc_skin_striae_bricks", inception.INCEPTION_TAB);
        final Block INC_WOOD_STRIPE_SMOOTH = new BlockBase(Material.ROCK, "inc_wood_stripe_smooth", inception.INCEPTION_TAB);
        final Block INC_OAK_SMOOTH = new BlockBase(Material.ROCK, "inc_oak_smooth", inception.INCEPTION_TAB);
        final Block INC_LOG_SMOOTH = new BlockBase(Material.ROCK, "inc_log_smooth", inception.INCEPTION_TAB);
        final Block INC_WOOD_STRIPE_LIGHT = new BlockBase(Material.ROCK, "inc_wood_stripe_light", inception.INCEPTION_TAB);
        final Block INC_FLANNEL = new BlockBase(Material.ROCK, "inc_flannel", inception.INCEPTION_TAB);
        final Block INC_REFLECTIVE_METAL = new BlockBase(Material.ROCK, "inc_reflective_metal", inception.INCEPTION_TAB);
        final Block INC_LATEX_MATTRESS = new BlockBase(Material.ROCK, "inc_latex_mattress", inception.INCEPTION_TAB);
        final Block INC_SAND = new BlockBase(Material.ROCK, "inc_sand", inception.INCEPTION_TAB);
        final Block INC_SPOTLIGHT = new BlockBase(Material.ROCK, "inc_spotlight", inception.INCEPTION_TAB);
        final Block INC_CONCRETE_DARK_GRAY = new BlockBase(Material.ROCK, "inc_concrete_dark_gray", inception.INCEPTION_TAB);
        final Block INC_LIMESTONE = new BlockBase(Material.ROCK, "inc_limestone", inception.INCEPTION_TAB);
        final Block INC_TATAMI = new BlockBase(Material.ROCK, "inc_tatami", inception.INCEPTION_TAB);
        final Block INC_RATTAN = new BlockBase(Material.ROCK, "inc_rattan", inception.INCEPTION_TAB);
        final Block INC_WOOD_STAGGER_VERTICAL = new BlockBase(Material.ROCK, "inc_wood_stagger_vertical", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_TOILET = new BlockBase(Material.ROCK, "inc_ceramic_toilet", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_SEAMLESS = new BlockBase(Material.ROCK, "inc_ceramic_seamless", inception.INCEPTION_TAB);
        final Block INC_WOOD_FINE_STRIPED = new BlockBase(Material.ROCK, "inc_wood_fine_striped", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_SCHOOL = new BlockBase(Material.ROCK, "inc_ceramic_school", inception.INCEPTION_TAB);
        final Block INC_CERAMIC_POOL = new BlockBase(Material.ROCK, "inc_ceramic_pool", inception.INCEPTION_TAB);
        final Block INC_CEMENT = new BlockBase(Material.ROCK, "inc_cement", inception.INCEPTION_TAB);
        icon = INC_CARPET_ONE;
    }

    public static ItemStack getIcon() {
        return new ItemStack(Item.getItemFromBlock(icon));
    }

}
